version: '3.7'

services:
  proxy:
    container_name: proxy
    image: carlonicora/proxy-alpine:1.17
    restart: always
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    volumes:
      - ./proxy/hosts:/etc/nginx/conf.d:delegated
      - ./proxy/includes:/etc/nginx/includes:delegated
      - ./proxy/logs:/logs/nginx:delegated
      - ./certbot/conf:/etc/letsencrypt:delegated
      - ./certbot/www:/var/www/certbot:delegated
    networks:
      - default_network
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  letsencrypt:
    container_name: letsencrypt
    image: certbot/certbot
    restart: always
    networks:
      - default_network
    volumes:
      - ./certbot/conf:/etc/letsencrypt:delegated
      - ./certbot/www:/var/www/certbot:delegated
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  host1:
    container_name: host1
    image: carlonicora/host1-nginx:1.17
    build:
      context: .
      dockerfile: ./host1/Dockerfile
    expose:
      - "80"
    volumes:
      - ./host1/html:/var/www/html:delegated
      - ./host1/logs:/logs/nginx:delegated
    networks:
      - default_network

  host2:
    container_name: host2
    image: carlonicora/host2-nginx:1.17
    build:
      context: .
      dockerfile: ./host2/Dockerfile
    expose:
      - "80"
    volumes:
      - ./host2/html:/var/www/html:delegated
      - ./host2/logs:/logs/nginx:delegated
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: carlonicora